### ISSUE TITLE
Link to the poster results in 404

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/M1NetworkModel#3]
This is probably related to:
https://github.com/Neurosim-lab/netpyne/issues/322

as both files share the same parent folder:
http://neurosimlab.org/salvadord/sfn15-sal-final.pdf

The same link is used in the pip documentation: https://pypi.org/project/netpyne/0.4.1/

**Comment by pgleeson** [comment]
Thanks @JustasB, fixed in same way as Neurosim-lab/netpyne#322.
