### ISSUE TITLE
Check license/citation

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/M1NetworkModel#4]
@salvadord We're just adding license info etc. to some OSB repos. Could you check this (MIT licence, req to cite NetPyNE paper in [CITATION.md](https://github.com/OpenSourceBrain/M1NetworkModel/blob/master/CITATION.md))?

**Comment by salvadord** [comment]
looks good, thanks!

**Comment by pgleeson** [comment]
Great!

**Comment by pgleeson** [comment]
FYI @salvadord I've added info to the Citation file linking to a zipped version of this repo on Zenodo: https://github.com/OpenSourceBrain/M1NetworkModel/blob/master/CITATION.md. 

This is to have a single DOI for people to refer to if they use the code in the repo (as I'm trying to do for all core OSB projects).  Any new release of this code on Github will automatically make a new Zenodo version (the DOI will link to the latest). There is still the request to cite the main NetPyNE paper.

**Comment by salvadord** [comment]
sounds good thx!
